# Generated by Django 5.1.1 on 2024-09-28 19:24

import CorralSnake.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=CorralSnake.utils.uuid_upload_to),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(null=True, upload_to=CorralSnake.utils.uuid_upload_to),
        ),
    ]
