# Generated by Django 5.1.1 on 2024-09-28 19:51

import CorralSnake.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_image_alter_questionanswer_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=CorralSnake.utils.uuid_upload_to),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(null=True, upload_to=CorralSnake.utils.uuid_upload_to),
        ),
        migrations.AlterField(
            model_name='submittedanswer',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
