# Generated by Django 5.1.1 on 2024-09-29 06:13

import CorralSnake.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quiz_image_alter_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=CorralSnake.utils.uuid_upload_to),
        ),
    ]
