# Generated by Django 5.1.1 on 2024-09-28 19:24

import CorralSnake.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(null=True, upload_to=CorralSnake.utils.uuid_upload_to)),
            ],
        ),
    ]
