# Generated by Django 5.1.1 on 2024-09-28 14:20

import CorralSnake.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=CorralSnake.utils.uuid_upload_to),
        ),
    ]
